<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Accepted' => 'Aceptado',
    'Add Game' => 'Añadir Juego',
    'Add Platform' => 'Añadir Plataforma',
    'Are you sure you want to leave this group?' => '¿Estás seguro de que quieres dejar este grupo?',
    'Collection' => 'Colección',
    'Cover' => 'Carátula',
    'Create' => 'Crear',
    'Create Group' => 'Crear grupo',
    'Create Platform' => 'Crear plataforma',
    'Developers' => 'Desarrolladores',
    'Game' => 'Juego',
    'Games' => 'Juegos',
    'Genre' => 'Género',
    'Groups' => 'Grupos',
    'Join' => 'Unirse',
    'Leave group' => 'Dejar grupo',
    'Manage Games' => 'Gestionar juegos',
    'Management' => 'Gestión',
    'Members' => 'Miembros',
    'Name' => 'Nombre',
    'Pending requests' => 'Solicitudes pendientes',
    'Platform' => 'Plataforma',
    'Platforms' => 'Plataforma',
    'Released' => 'Publicado',
    'Requests' => 'Solicitudes',
    'Reset' => 'Reiniciar',
    'Role' => 'Rol',
    'Search' => 'Buscar',
    'Select Cover' => 'Seleccionar Carátula',
    'There was a problem submitting your request' => 'Ha habido un problema al enviar su solicitud',
    'Type' => 'Tipo',
    'Update' => 'Actualizar',
    'Update {modelClass}: ' => 'Actualizar {modelClass}:',
    'Your request is pending of being valued' => 'TU solicitud está pendiente de ser valorada',
    'update' => 'actualizar',
    'My Profile' => 'Mi Perfil',
    'Configuration' => 'Configuración',
    'Logout' => 'Cerrar sesión',
    'Sign up' => 'Registrarse',
    'Sign in' => 'Iniciar sesión',
    'Users' => 'Usuarios',
    'Repeat Password' => 'Repetir Contraseña',
    'Delete account' => 'Borrar Cuenta',
    'Once you delete your account, there is no going back' => 'Una vez borres tu cuenta, no hay vuelta atrás',
    'It will be deleted forever' => 'Se borrará para siempre',
    'Please be certain' => 'Asegúrate de querer hacerlo',
    'Are you sure? There is no going back' => '¿Estás seguro? No hay vuelta atrás',
    'Your name' => 'Tu nombre',
    'Gender' => 'Género',
    'Time zone' => 'Zona horaria',
    'Game collection' => 'Colección de juegos',
    'The game {game} ({platform}) has been added' => 'Se ha añadido el juego {game} ({platform})',
    'The game {game} ({platform}) has been deleted'  => 'Se ha eliminado el juego {game} ({platform})',
    'Messages' => 'Mensajes',
    'New message' => 'Nuevo mensaje',
    'New Message' => 'Nuevo Mensaje',
    'Find user' => 'Buscar usuario',
    'Send message' => 'Enviar mensaje',
    'Send' => 'Enviar',
    'Show old messages' => 'Mostrar mensajes antiguos',
    'No messages left' => 'No hay más mensajes',
    'Content' => 'Contenido'
];
