<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Assignments have been updated' => 'Las asignaciones se han actualizado',
    'Auth item with such name already exists' => 'Ya existe un elemento auth con ese nombre',
    'Children' => 'Hijos',
    'Class "{0}" does not exist' => 'La clase "{0}" no existe',
    'Create' => 'Crear',
    'Create new permission' => 'Crear nuevo permiso',
    'Create new role' => 'Crear nuevo rol',
    'Description' => 'Descripción',
    'Invalid value' => 'Valor inválido',
    'Item has been created' => 'Se ha creado el elemento',
    'Item has been updated' => 'Se ha actualizado el elemento',
    'Items' => 'Elementos',
    'Name' => 'Nombre',
    'New permission' => 'Nuevo permiso',
    'New role' => 'Nuevo rol',
    'New rule' => 'Nuevo regla',
    'New user' => 'Nuevo usuario',
    'Permissions' => 'Permisos',
    'Roles' => 'Roles',
    'Rule' => 'Regla',
    'Rules' => 'Reglas',
    'Rule class can not be instantiated' => 'No se puede instanciar la clase de la regla',
    'Rule class must extend "yii\rbac\Rule"' => 'La clase de la regla debe extender "yii\rbac\Rule"',
    'Rule name' => 'Nombre de la regla',
    'Save' => 'Guardar',
    'There is neither role nor permission with name "{0}"' => 'No hay reglas o permisos con el nombre "{0}"',
    'Update assignments' => 'Actualizar asignaciones',
    'Update permission' => 'Actualizar permiso',
    'Update role' => 'Actualizar rol',
    'Users' => 'Usuarios',
    'Created at' => 'Creado',
    'Updated at' => 'Actualizado',
    'Class' => 'Clase',
    'Select role' => 'Seleccionar rol',
    'Select rule' => 'Seleccionar regla',
    'Select permission' => 'Seleccionar permiso',
    'Enter the description' => 'Introduzca la descripción',
    'Data' => 'datos',

];
